In [1]:
import pandas as pd

In [5]:
base_gps = pd.read_csv("comparativo_programado_executado_com_nucleo.csv", sep=";")

In [6]:
base_gps

,Linha,Faixa_Horaria,Executado,Programado,tipo_dia,% Execução,Núcleo
0,108,03/jun,14,0,NaN,0.0,Gentileza
1,108,06/set,35,0,NaN,0.0,Gentileza
2,108,09/dez,33,0,NaN,0.0,Gentileza
3,108,dez/15,28,0,NaN,0.0,Gentileza
4,108,15-18,30,35,Dia Útil,85.7,Gentileza
...,...,...,...,...,...,...,...
81,SV112,09/dez,16,0,NaN,0.0,Gentileza
82,SV112,dez/15,17,0,NaN,0.0,Gentileza
83,SV112,15-18,16,18,Dia Útil,88.9,Gentileza
84,SV112,18-21,17,20,Dia Útil,85.0,Gentileza
85,SV112,21-00,5,4,Dia Útil,125.0,Gentileza